name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    container: ubuntu:22.04

    steps:
    - uses: actions/checkout@v5

    - name: fetch prerequisites
      run: |
        apk add --no-cache \
          coreutils \
          curl \
          gcc \
          make \
          musl-dev \
          openssl-dev

    - name: fetch source
      run: |
        set -ex

        DOWNLOADURL=https://github.com/redis/redis/archive/refs/tags/7.2.0.tar.gz
        curl -L ${DOWNLOADURL} | tar xz --strip-components=1

        set +ex

    - name: make
      run: |
        make CFLAGS="-static" LDFLAGS="-static" BUILD_TLS=yes

    - name: make test
      run: |
        apk add --no-cache \
          tcl

        cat > tests_to_skip <<EOF
        integration/psync2-reg
        integration/failover
        EOF

        # static builds don't produce stacktrace as expected by test
        # (see https://github.com/redis/redis/issues/4135)
        # and aren't properly detected by tests/integration/logging.tcl.
        # So forcefully ignore them by editing test out of script.
        sed -i '/} elseif {$system_name eq {linux}} {/d' tests/integration/logging.tcl

        ./runtest

    - name: store build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: |
          src/redis-cli
          src/redis-sentinel
          src/redis-server

    - name: Release (if tagged)
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          src/redis-cli
          src/redis-sentinel
          src/redis-server
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
